### ISSUE TITLE
"All Matches" list is not showing the matches

### ISSUE THREAD

**Issue by legomann97** [mortorqrobotics/MorScout#7]
I am participating in the East Arizona Regional, and I have input the "2015azch" code into the url file. The app is showing the teams competing in the event and is allowing pit scouting, but the All Matches tab has nothing but the search bar and the bar that has "#, Time, Progress, Red Teams, Blue Teams" on it. There is nothing underneath it.

Thank you,
Chris Gomez

**Comment by Farbod909** [comment]
Dear Mr. Gomez,
If your regional's actual matches(not practice matches) start on Friday, then the match information from the blue alliance will be updated in the morning of that day. This is because we get our match data from thebluealliance.com and they decide to update their match data on the day that the matches start. Once again, thanks for using morscout!
Best Regards,
Farbod Rafezy
